name: Deploy to Github Packages

on:
  push:
    branches: [main]

jobs:
  deploy_to_github_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Update Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release

      - name: Build Web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: touch .nojekyll && yarn build && yarn export

      - name: Deploy Web
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
