name: Deploy to Github Pages

on:
  push:
    branches: [main]

jobs:
  deploy_to_github_packages:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        run: yarn ci-install

      - name: Build Web
        run: yarn ci-build

      - name: Deploy Web
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
