name: Validate PR Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate_commits:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
